export const employeeprofiles =
  // [
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      supervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  }
  // {
  //   publicProfile: {
  //     name: "Julian Sallee",
  //     linkedIn: "https://www.linkedin.com/",
  //     gender: "Female",
  //     email: "elisabeth.rudolf@demo-sample.com",
  //     office: "Muchen",
  //     department: "Marketing and Sales",
  //     position: "Junior Sales Manager",
  //     team: "Sales",
  //   },
  //   hrInfo: {
  //     fname: "Julian",
  //     lname: "Sallee",
  //     empId: "11729",
  //     bday: "27",
  //     bmonth: "10",
  //     byear: "1980",
  //     status: "active",
  //     employmentType: "Internal",
  //     nationality: "Deutschland",
  //     cert: "Not yet",
  //     hday: "01",
  //     hmonth: "03",
  //     hyear: "2011",
  //     noticeperiod: "3 Monate zum Monatsende",
  //     contractends: "Not set",
  //     occupationtype: "Festanstellung",
  //     costcenter: "Not set",
  //     supervisor: {
  //       supervisorImg:
  //         "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
  //       supervisorName: "Laura Erdmann",
  //     },
  //     lengthProbation: "6 months",
  //     weeklyhours: 40,
  //     children: false,
  //   },
  //   personalData: {
  //     street: "Luisenring",
  //     houseNum: "54",
  //   },
  // },
  // {
  //   publicProfile: {
  //     name: "Elpedia Arthur",
  //     linkedIn: "https://www.linkedin.com/",
  //     gender: "Female",
  //     email: "elisabeth.rudolf@demo-sample.com",
  //     office: "Muchen",
  //     department: "Marketing and Sales",
  //     position: "Junior Sales Manager",
  //     team: "Sales",
  //   },
  //   hrInfo: {
  //     fname: "Elpedia",
  //     lname: "Arthur",
  //     empId: "11729",
  //     bday: "27",
  //     bmonth: "10",
  //     byear: "1980",
  //     status: "active",
  //     employmentType: "Internal",
  //     nationality: "Deutschland",
  //     cert: "Not yet",
  //     hday: "01",
  //     hmonth: "03",
  //     hyear: "2011",
  //     noticeperiod: "3 Monate zum Monatsende",
  //     contractends: "Not set",
  //     occupationtype: "Festanstellung",
  //     costcenter: "Not set",
  //     supervisor: {
  //       supervisorImg:
  //         "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
  //       supervisorName: "Laura Erdmann",
  //     },
  //     lengthProbation: "6 months",
  //     weeklyhours: 40,
  //     children: false,
  //   },
  //   personalData: {
  //     street: "Luisenring",
  //     houseNum: "54",
  //   },
  // },
// ];


export const allemployeesprofile =
  [
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
      img: "https://cdn-icons-png.flaticon.com/512/1077/1077114.png"
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
      img: "https://lh3.googleusercontent.com/EbXw8rOdYxOGdXEFjgNP8lh-YAuUxwhOAe2jhrz3sgqvPeMac6a6tHvT35V6YMbyNvkZL4R_a2hcYBrtfUhLvhf-N2X3OB9cvH4uMw=w1064-v0"
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBA9-3gshYFwDoSerwZ-DTl5mUA0qIbP8sL9afe26eHLocJjKYcNI7-mmwnhuQ6hE-TGE&usqp=CAU"
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
      img: "https://upload.wikimedia.org/wikipedia/commons/d/d4/Icone_appareil_photo.svg"
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBTTe3j_xiVsYhXdncw2bTdJjp6MtTgtSHgSvFnCn86SXfXcioUA_Ca6b5CslQn4uoBMc&usqp=CAU"
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },{
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Sales Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elpedia Arthur",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elpediaarthurjunior@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Technical Lead",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Elpedia",
      "Last Name (legal)": "Arthur",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Customer Service",
      Position: "Cutomer Service Manager",
      Team: "Customer Service",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Julian Sallee",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "juliansallee.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Key Account Manager",
      Team: "Sales",
    },
    HRInformation: {
      "First name (legal)": "Julian",
      "Last name (legal)": "Sallee",
      "Employee ID": "11729",
      Birthday: "🎂 30/01/1999 (25 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Laura Erdmann",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  },
  {
    publicProfile: {
      Name: "Samuel Mensah",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "samuelmensah@gmail.com",
      Office: "Muchen",
      Department: "IT",
      Position: "Project Manager",
      Team: "Product",
    },
    HRInformation: {
      "First Name (legal)": "Samuel",
      "Last Name (legal)": "Mensah",
      "Employee ID": "11729",
      Birthday: "🎂 30/10/1997 (27 years)",
      Status: "active",
      "Employment Type": "Internal",
      Nationality: "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      SupervisorName: "Herman MN Angabo",
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      street: "Luisenring",
      houseNum: "54",
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  }

];
