export const employeeprofiles =
  // [
  {
    publicProfile: {
      Name: "Elisabeth Rudolf",
      LinkedIn: "https://www.linkedin.com/",
      Gender: "Female",
      Email: "elisabeth.rudolf@demo-sample.com",
      Office: "Muchen",
      Department: "Marketing and Sales",
      Position: "Junior Sales Manager",
      Team: "Sales",
      img: "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
    },
    HRInformation: {
      "First name (legal)": "Elisabeth",
      "Last name (legal)": "Rudolf",
      "Employee ID": "11729",
      Birthday: "🎂 27/10/1980 (44 years)",
      Status: "Active",
      "Employment Type": "Internal",
      "Nationality": "Deutschland",
      "Enrolment certificare valid until": "Not set",
      "Hire date": "📆 01/03/2011",
      "Notice period": "3 Monate zum Monatsende",
      "Contract ends ℹ️": "Not set",
      "Occupation type": "Festanstellung",
      "Cost center": "Not set",
      // supervisor: {
      //   supervisorImg:
      //     "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
      //   supervisorName: "Laura Erdmann",
      // },
      "Length Probation": "6 months",
      "Weekly hours": 40,
      "Children ℹ️": "Not set",
    },
    personalData: {
      Street: "Luisenring",
      "House number": "54",
      Postcode: "80797",
      City: "Muchen"
    },
    payrollInformation: {
      "Tax ID": "999999999999",
      "Social security number": "12345678 A 912",
      "Personal income tax class": 1,
      "Marital Status": "Nein",
      "Religious denomination": "rk - Romisch-Katholische Kirchensteuer",
      "Type of health insurance": "Gesetzlich krankenversichert",
    },
    bankDetails:{
      "Bank company": "Scotia Bank",
      "Card number": "4536 1234 7890 3456",
      "Expiry date": "01/26",
      "Security code": "345",
    },
    emergencyContact:{
      "Contact name": "Elpedia J. Arthur",
      "Contact phone": "+233 59 796 1103",
      "Relationship": "Mother",
    }
  };
  // {
  //   publicProfile: {
  //     name: "Julian Sallee",
  //     linkedIn: "https://www.linkedin.com/",
  //     gender: "Female",
  //     email: "elisabeth.rudolf@demo-sample.com",
  //     office: "Muchen",
  //     department: "Marketing and Sales",
  //     position: "Junior Sales Manager",
  //     team: "Sales",
  //   },
  //   hrInfo: {
  //     fname: "Julian",
  //     lname: "Sallee",
  //     empId: "11729",
  //     bday: "27",
  //     bmonth: "10",
  //     byear: "1980",
  //     status: "active",
  //     employmentType: "Internal",
  //     nationality: "Deutschland",
  //     cert: "Not yet",
  //     hday: "01",
  //     hmonth: "03",
  //     hyear: "2011",
  //     noticeperiod: "3 Monate zum Monatsende",
  //     contractends: "Not set",
  //     occupationtype: "Festanstellung",
  //     costcenter: "Not set",
  //     supervisor: {
  //       supervisorImg:
  //         "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
  //       supervisorName: "Laura Erdmann",
  //     },
  //     lengthProbation: "6 months",
  //     weeklyhours: 40,
  //     children: false,
  //   },
  //   personalData: {
  //     street: "Luisenring",
  //     houseNum: "54",
  //   },
  // },
  // {
  //   publicProfile: {
  //     name: "Elpedia Arthur",
  //     linkedIn: "https://www.linkedin.com/",
  //     gender: "Female",
  //     email: "elisabeth.rudolf@demo-sample.com",
  //     office: "Muchen",
  //     department: "Marketing and Sales",
  //     position: "Junior Sales Manager",
  //     team: "Sales",
  //   },
  //   hrInfo: {
  //     fname: "Elpedia",
  //     lname: "Arthur",
  //     empId: "11729",
  //     bday: "27",
  //     bmonth: "10",
  //     byear: "1980",
  //     status: "active",
  //     employmentType: "Internal",
  //     nationality: "Deutschland",
  //     cert: "Not yet",
  //     hday: "01",
  //     hmonth: "03",
  //     hyear: "2011",
  //     noticeperiod: "3 Monate zum Monatsende",
  //     contractends: "Not set",
  //     occupationtype: "Festanstellung",
  //     costcenter: "Not set",
  //     supervisor: {
  //       supervisorImg:
  //         "https://images.unsplash.com/photo-1615751072497-5f5169febe17?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80",
  //       supervisorName: "Laura Erdmann",
  //     },
  //     lengthProbation: "6 months",
  //     weeklyhours: 40,
  //     children: false,
  //   },
  //   personalData: {
  //     street: "Luisenring",
  //     houseNum: "54",
  //   },
  // },
// ];
